[project]
name = "consuma"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.128.0",
    "aiosqlite>=0.20.0",
    "httpx>=0.27.0",
    "aiohttp>=3.9.0",
]
